### PR TITLE
Update ToolbarExtender.cs

### PR DESCRIPTION
**Pull request by Frank-99**
in 2019 the center buttons are 140 of width instead of 100, as it was in 2018.
While fixing that, I thought that the "StandardDimensions" would have been a nice feature, but if you think it's better without it, I can remove it from my edit before you accept the pull request! :)

### CODE REVIEW

**Review by marijnz — COMMENTED** [review]
Hey, what about just writing down the constants once, directly in the method? So without the extra class. I see you suggest that already as well and I agree! :)

**Comment by Frank-99** [comment]
I see, I edited it that way so that in my project I'm able to access it from my custom button GUI method and keep everything more neat and "standard"...
Here I made it as you asked for the pull request though :)

BTW, I wanted to say that while looking around I found the unite 2017 video and I was very mesmerised, it gave me a lot of great ideas for some tools I'm making, and some great others to fix issues I have! :D

**Comment by marijnz** [comment]
Hey, completely missed this thread. Great to hear the talk is helping you!

**Review by marijnz — APPROVED** [review]

**Comment by brogan89** [comment]
how come this has been approved but not merged? This commit is important for supporting new unity editor.

**Pull request merged**
