### PR TITLE
Alternative way (UIElements) improvements

### PR DESCRIPTION
**Pull request by marijnz**
#6 with: 

- Screen.width was giving the resolution of my screen, not the downscaled Unity resolution which is half of it. EditorGUIUtility.currentViewWidth fixed it for me.
- Improved naming (but I'm open to changes)
- Tabs instead of spaces to stay consistent
- Using the proper Scene icon in the SceneViewFocuser example, it's now light with the dark theme

Tested with Unity 2018.2 and 2017.3 Mac and Unity 2018.2 on VM Windows 10. All works!

### CODE REVIEW

**Comment by marijnz** [comment]
@OndrejPetrzilka Your new way is great. I made a new branch for some changes on it, let me know what you think. I will also update the readme when we merge. We could make another Reddit post.

**Review by OndrejPetrzilka — APPROVED** [review]
Good idea with `EditorGUIUtility.currentViewWidth`, how is the height for you, is it okay?

**Comment by marijnz** [comment]
I thought it was, but maybe wasn't looking close enough. Will check later today

**Comment by marijnz** [comment]
Yes it works fine 👍

**Pull request merged**
