### PR TITLE
Fix non expanding IMGUIContainer

### PR DESCRIPTION
**Pull request by gjh33**
IMGUIContainer now expands so flexible space works correctly

### CODE REVIEW

**Comment by XtroTheArctic** [comment]
This is a HUGE life saver. Thank you!!

Must be merged if the author is still around. (Hopefully)

**Comment by gjh33** [comment]
> This is a HUGE life saver. Thank you!!
> 
> Must be merged if the author is still around. (Hopefully)

It's been here for awhile so I'm not so sure. But I'm glad it helped you!

**Comment by marijnz** [comment]
> > This is a HUGE life saver. Thank you!!
> > 
> > Must be merged if the author is still around. (Hopefully)
> 
> It's been here for awhile so I'm not so sure. But I'm glad it helped you!

Done!

**Comment by marijnz** [comment]
Also created new release for it

**Pull request merged**
